# Generated by Django 3.2.8 on 2021-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.CharField(default='test', max_length=45),
        ),
    ]
